// This file is @generated by `gen.py`

// --- mime.txt ----------------------------------------------------------------

#[derive(Clone)]
pub(crate) enum ContentTypeInner {
    Plain,
    Html,
    Css,
    Js,
    Svg,
    Latex,
    Pdf,
    Woff,
    Woff2,
    Ttf,
    Otf,
    Png,
    Jpg,
    Jpeg,
    Webp,
    Gif,
    Ico,
    Json,
    Xml,
    Map,
    Wasm,
    Mp4,
    Webm,
    Mp3,
    Ogg,
    Default,
    Custom(String),
}

impl ContentTypeInner {
    pub(crate) fn as_str(&self) -> &str {
        match self {
            Self::Plain => "text/plain; charset=utf-8",
            Self::Html => "text/html; charset=utf-8",
            Self::Css => "text/css; charset=utf-8",
            Self::Js => "text/javascript",
            Self::Svg => "image/svg+xml; charset=utf-8",
            Self::Latex => "application/x-latex; charset=utf-8",
            Self::Pdf => "application/pdf",
            Self::Woff => "font/woff",
            Self::Woff2 => "font/woff2",
            Self::Ttf => "font/ttf",
            Self::Otf => "font/otf",
            Self::Png => "image/png",
            Self::Jpg => "image/jpeg",
            Self::Jpeg => "image/jpeg",
            Self::Webp => "image/webp",
            Self::Gif => "image/gif",
            Self::Ico => "image/x-icon",
            Self::Json => "application/json",
            Self::Xml => "application/xml; charset=utf-8",
            Self::Map => "application/json",
            Self::Wasm => "application/wasm",
            Self::Mp4 => "video/mp4",
            Self::Webm => "video/webm",
            Self::Mp3 => "audio/mpeg",
            Self::Ogg => "audio/ogg",
            Self::Default => "application/octet-stream",
            Self::Custom(s) => s.as_str(),
        }
    }
}

/// A content type (MIME type) for HTTP responses.
#[derive(Clone)]
pub struct ContentType(pub(crate) ContentTypeInner);

impl ContentType {
    /// Returns the content type for the given file extension (without leading dot),
    /// or `None` if the extension is not recognised.
    pub fn from_extension(ext: Option<&str>) -> Option<Self> {
        match ext {
            Some("txt") => Some(Self::PLAIN),
            Some("html") => Some(Self::HTML),
            Some("css") => Some(Self::CSS),
            Some("js") => Some(Self::JS),
            Some("svg") => Some(Self::SVG),
            Some("tex") => Some(Self::LATEX),
            Some("pdf") => Some(Self::PDF),
            Some("woff") => Some(Self::WOFF),
            Some("woff2") => Some(Self::WOFF2),
            Some("ttf") => Some(Self::TTF),
            Some("otf") => Some(Self::OTF),
            Some("png") => Some(Self::PNG),
            Some("jpg") => Some(Self::JPG),
            Some("jpeg") => Some(Self::JPEG),
            Some("webp") => Some(Self::WEBP),
            Some("gif") => Some(Self::GIF),
            Some("ico") => Some(Self::ICO),
            Some("json") => Some(Self::JSON),
            Some("xml") => Some(Self::XML),
            Some("map") => Some(Self::MAP),
            Some("wasm") => Some(Self::WASM),
            Some("mp4") => Some(Self::MP4),
            Some("webm") => Some(Self::WEBM),
            Some("mp3") => Some(Self::MP3),
            Some("ogg") => Some(Self::OGG),
            _ => None,
        }
    }

    /// The `text/plain; charset=utf-8` content type.
    pub const PLAIN: Self = ContentType(ContentTypeInner::Plain);
    /// The `text/html; charset=utf-8` content type.
    pub const HTML: Self = ContentType(ContentTypeInner::Html);
    /// The `text/css; charset=utf-8` content type.
    pub const CSS: Self = ContentType(ContentTypeInner::Css);
    /// The `text/javascript` content type.
    pub const JS: Self = ContentType(ContentTypeInner::Js);
    /// The `image/svg+xml; charset=utf-8` content type.
    pub const SVG: Self = ContentType(ContentTypeInner::Svg);
    /// The `application/x-latex; charset=utf-8` content type.
    pub const LATEX: Self = ContentType(ContentTypeInner::Latex);
    /// The `application/pdf` content type.
    pub const PDF: Self = ContentType(ContentTypeInner::Pdf);
    /// The `font/woff` content type.
    pub const WOFF: Self = ContentType(ContentTypeInner::Woff);
    /// The `font/woff2` content type.
    pub const WOFF2: Self = ContentType(ContentTypeInner::Woff2);
    /// The `font/ttf` content type.
    pub const TTF: Self = ContentType(ContentTypeInner::Ttf);
    /// The `font/otf` content type.
    pub const OTF: Self = ContentType(ContentTypeInner::Otf);
    /// The `image/png` content type.
    pub const PNG: Self = ContentType(ContentTypeInner::Png);
    /// The `image/jpeg` content type.
    pub const JPG: Self = ContentType(ContentTypeInner::Jpg);
    /// The `image/jpeg` content type.
    pub const JPEG: Self = ContentType(ContentTypeInner::Jpeg);
    /// The `image/webp` content type.
    pub const WEBP: Self = ContentType(ContentTypeInner::Webp);
    /// The `image/gif` content type.
    pub const GIF: Self = ContentType(ContentTypeInner::Gif);
    /// The `image/x-icon` content type.
    pub const ICO: Self = ContentType(ContentTypeInner::Ico);
    /// The `application/json` content type.
    pub const JSON: Self = ContentType(ContentTypeInner::Json);
    /// The `application/xml; charset=utf-8` content type.
    pub const XML: Self = ContentType(ContentTypeInner::Xml);
    /// The `application/json` content type.
    pub const MAP: Self = ContentType(ContentTypeInner::Map);
    /// The `application/wasm` content type.
    pub const WASM: Self = ContentType(ContentTypeInner::Wasm);
    /// The `video/mp4` content type.
    pub const MP4: Self = ContentType(ContentTypeInner::Mp4);
    /// The `video/webm` content type.
    pub const WEBM: Self = ContentType(ContentTypeInner::Webm);
    /// The `audio/mpeg` content type.
    pub const MP3: Self = ContentType(ContentTypeInner::Mp3);
    /// The `audio/ogg` content type.
    pub const OGG: Self = ContentType(ContentTypeInner::Ogg);
    /// The default (`application/octet-stream`) content type.
    pub const DEFAULT: Self = ContentType(ContentTypeInner::Default);
}

// --- method.txt --------------------------------------------------------------

/// An HTTP request method.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    GET,
    POST,
    PUT,
    DELETE,
    PATCH,
    HEAD,
    OPTIONS,
}

impl Method {
    /// Parses an HTTP method from its byte representation.
    pub fn from_bytes(s: &[u8]) -> Option<Self> {
        match s {
            b"GET" => Some(Self::GET),
            b"POST" => Some(Self::POST),
            b"PUT" => Some(Self::PUT),
            b"DELETE" => Some(Self::DELETE),
            b"PATCH" => Some(Self::PATCH),
            b"HEAD" => Some(Self::HEAD),
            b"OPTIONS" => Some(Self::OPTIONS),
            _ => None,
        }
    }

    /// Returns the string representation of the HTTP method.
    pub fn as_str(self) -> &'static str {
        match self {
            Method::GET => "GET",
            Method::POST => "POST",
            Method::PUT => "PUT",
            Method::DELETE => "DELETE",
            Method::PATCH => "PATCH",
            Method::HEAD => "HEAD",
            Method::OPTIONS => "OPTIONS",
        }
    }
}

// --- status_code.txt ---------------------------------------------------------

/// An HTTP status code.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StatusCode {
    /// HTTP/1.1 200 OK
    Ok,
    /// HTTP/1.1 307 Temporary Redirect
    TemporaryRedirect,
    /// HTTP/1.1 400 Bad Request
    BadRequest,
    /// HTTP/1.1 403 Forbidden
    Forbidden,
    /// HTTP/1.1 404 Not Found
    NotFound,
    /// HTTP/1.1 405 Method Not Allowed
    MethodNotAllowed,
    /// HTTP/1.1 408 Request Timeout
    RequestTimeout,
    /// HTTP/1.1 413 Content Too Large
    ContentTooLarge,
    /// HTTP/1.1 501 Not Implemented
    NotImplemented,
    /// HTTP/1.1 503 Service Unavailable
    ServiceUnavailable,
}

impl StatusCode {
    /// Returns the numeric status code.
    pub fn as_u16(self) -> u16 {
        match self {
            Self::Ok => 200,
            Self::TemporaryRedirect => 307,
            Self::BadRequest => 400,
            Self::Forbidden => 403,
            Self::NotFound => 404,
            Self::MethodNotAllowed => 405,
            Self::RequestTimeout => 408,
            Self::ContentTooLarge => 413,
            Self::NotImplemented => 501,
            Self::ServiceUnavailable => 503,
        }
    }

    /// Returns the reason phrase (e.g. `"OK"`, `"Not Found"`).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Ok => "OK",
            Self::TemporaryRedirect => "Temporary Redirect",
            Self::BadRequest => "Bad Request",
            Self::Forbidden => "Forbidden",
            Self::NotFound => "Not Found",
            Self::MethodNotAllowed => "Method Not Allowed",
            Self::RequestTimeout => "Request Timeout",
            Self::ContentTooLarge => "Content Too Large",
            Self::NotImplemented => "Not Implemented",
            Self::ServiceUnavailable => "Service Unavailable",
        }
    }
}

// --- header_name.txt ---------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum HeaderNameInner {
    ContentType,
    Location,
    CacheControl,
    ContentDisposition,
    SetCookie,
    AccessControlAllowOrigin,
    AccessControlAllowMethods,
    AccessControlAllowHeaders,
    AccessControlAllowCredentials,
    AccessControlMaxAge,
    AccessControlExposeHeaders,
    StrictTransportSecurity,
    XContentTypeOptions,
    XFrameOptions,
    Custom(String),
}

impl HeaderNameInner {
    pub(crate) fn as_str(&self) -> &str {
        match self {
            Self::ContentType => "Content-Type",
            Self::Location => "Location",
            Self::CacheControl => "Cache-Control",
            Self::ContentDisposition => "Content-Disposition",
            Self::SetCookie => "Set-Cookie",
            Self::AccessControlAllowOrigin => "Access-Control-Allow-Origin",
            Self::AccessControlAllowMethods => "Access-Control-Allow-Methods",
            Self::AccessControlAllowHeaders => "Access-Control-Allow-Headers",
            Self::AccessControlAllowCredentials => "Access-Control-Allow-Credentials",
            Self::AccessControlMaxAge => "Access-Control-Max-Age",
            Self::AccessControlExposeHeaders => "Access-Control-Expose-Headers",
            Self::StrictTransportSecurity => "Strict-Transport-Security",
            Self::XContentTypeOptions => "X-Content-Type-Options",
            Self::XFrameOptions => "X-Frame-Options",
            Self::Custom(s) => s.as_str(),
        }
    }
}

/// An HTTP header name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeaderName(pub(crate) HeaderNameInner);

impl HeaderName {
    /// The `Content-Type` header.
    pub const CONTENT_TYPE: Self = HeaderName(HeaderNameInner::ContentType);
    /// The `Location` header.
    pub const LOCATION: Self = HeaderName(HeaderNameInner::Location);
    /// The `Cache-Control` header.
    pub const CACHE_CONTROL: Self = HeaderName(HeaderNameInner::CacheControl);
    /// The `Content-Disposition` header.
    pub const CONTENT_DISPOSITION: Self = HeaderName(HeaderNameInner::ContentDisposition);
    /// The `Set-Cookie` header.
    pub const SET_COOKIE: Self = HeaderName(HeaderNameInner::SetCookie);
    /// The `Access-Control-Allow-Origin` header.
    pub const ACCESS_CONTROL_ALLOW_ORIGIN: Self =
        HeaderName(HeaderNameInner::AccessControlAllowOrigin);
    /// The `Access-Control-Allow-Methods` header.
    pub const ACCESS_CONTROL_ALLOW_METHODS: Self =
        HeaderName(HeaderNameInner::AccessControlAllowMethods);
    /// The `Access-Control-Allow-Headers` header.
    pub const ACCESS_CONTROL_ALLOW_HEADERS: Self =
        HeaderName(HeaderNameInner::AccessControlAllowHeaders);
    /// The `Access-Control-Allow-Credentials` header.
    pub const ACCESS_CONTROL_ALLOW_CREDENTIALS: Self =
        HeaderName(HeaderNameInner::AccessControlAllowCredentials);
    /// The `Access-Control-Max-Age` header.
    pub const ACCESS_CONTROL_MAX_AGE: Self = HeaderName(HeaderNameInner::AccessControlMaxAge);
    /// The `Access-Control-Expose-Headers` header.
    pub const ACCESS_CONTROL_EXPOSE_HEADERS: Self =
        HeaderName(HeaderNameInner::AccessControlExposeHeaders);
    /// The `Strict-Transport-Security` header.
    pub const STRICT_TRANSPORT_SECURITY: Self =
        HeaderName(HeaderNameInner::StrictTransportSecurity);
    /// The `X-Content-Type-Options` header.
    pub const X_CONTENT_TYPE_OPTIONS: Self = HeaderName(HeaderNameInner::XContentTypeOptions);
    /// The `X-Frame-Options` header.
    pub const X_FRAME_OPTIONS: Self = HeaderName(HeaderNameInner::XFrameOptions);
}
