name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo check
      - if: github.ref == 'refs/heads/main'
        run: python3 gen_date_tests.py > src/date_test_cases.txt
      - if: github.ref == 'refs/heads/main'
        run: cargo test
